set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS 
    "-DCMAKE_PLATFORM_NO_VERSIONED_SONAME=ON"
    "-DCMAKE_SHARED_LIBRARY_PREFIX="
    "-DCMAKE_STATIC_LIBRARY_PREFIX="
    "-DCMAKE_C_OUTPUT_EXTENSION_CHARS="
    "-DCMAKE_SHARED_LIBRARY_PREFIX_C="
    "-DCMAKE_SHARED_LIBRARY_PREFIX_CXX="
)